opt:
  lr: 0.0006
  weight_decay: 0.1
trainer:
  max_epochs: 2
  lr: 0.0006
  batch_size: 216
  data_loader_workers: 4
  enable_profile: False
model:
  n_layer: 8
  n_head: 8
  n_embd: 512
charnn:
  # train or generate
  task: train
  # started string
  phrase: Hello there

hydra:
  run:
    dir: ./
