Region: us-west-2
Image:
  Os: ubuntu1804
HeadNode:
  InstanceType: c4.xlarge
  Networking:
    # MODIFY THIS TO THE VALUE OF SUBNET ID
    SubnetId: YOUR_SUBNET_ID
  Ssh:
    # MODIFY THIS TO THE VALUE OF $AWS_KEY_NAME
    KeyName: AWS_KEY_NAME
  Iam:
    S3Access:
      # MODIFY THIS TO THE VALUE OF S3_BUCKET_NAME
      - BucketName: S3_BUCKET_NAME

Scheduling:
  Scheduler: slurm
  SlurmQueues:
    - Name: train
      ComputeResources:
        - Name: p38xlarge
          InstanceType: p3.8xlarge
          MinCount: 0
          MaxCount: 4
        - Name: p32xlarge
          InstanceType: p3.2xlarge
          MinCount: 0
          MaxCount: 4
      Networking:
        SubnetIds:
          # MODIFY THIS TO THE VALUE OF SUBNET ID
          - YOUR_SUBNET_ID
Monitoring:
  DetailedMonitoring: true
  Logs:
    CloudWatch:
      Enabled: true
      RetentionInDays: 14
  Dashboards:
    CloudWatch:
      Enabled: true
SharedStorage:
  - MountDir: /shared
    Name: shared-fs
    StorageType: FsxLustre
    FsxLustreSettings:
      StorageCapacity: 1200
      DeploymentType: SCRATCH_1
      StorageType: SSD


Tags:
  - Key: cluster
    Value: train-cluster
